### ISSUE TITLE
Exception when creating Visio

### ISSUE THREAD

**Issue by rappen** [LinkeD365/FlowToVisio#6]
Selected a flow from a solution.
Entered a filename.
Clicked Create Viso.

Got this:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at LinkeD365.FlowToVisio.HttpAction..ctor(JProperty property, Action parent, Int32 current, Int32 children)
   at LinkeD365.FlowToVisio.Utils.AddAction(JProperty actionProperty, Action parent, Int32 curCount, Int32 childCount)
   at LinkeD365.FlowToVisio.Utils.AddActions(IEnumerable`1 childActions, Action parent)
   at LinkeD365.FlowToVisio.Utils.AddActions(IEnumerable`1 childActions, Action parent)
   at LinkeD365.FlowToVisio.Utils.AddActions(IEnumerable`1 childActions, Action parent)
   at LinkeD365.FlowToVisio.Utils.AddActions(IEnumerable`1 childActions, Action parent)
   at LinkeD365.FlowToVisio.Utils.AddActions(IEnumerable`1 childActions, Action parent)
   at LinkeD365.FlowToVisio.Utils.AddActions(IEnumerable`1 childActions, Action parent)
   at LinkeD365.FlowToVisio.Utils.AddActions(IEnumerable`1 childActions, Action parent)
   at LinkeD365.FlowToVisio.Utils.AddActions(IEnumerable`1 childActions, Action parent)
   at LinkeD365.FlowToVisio.Utils.AddActions(IEnumerable`1 childActions, Action parent)
   at LinkeD365.FlowToVisio.Utils.AddActions(IEnumerable`1 childActions, Action parent)
   at LinkeD365.FlowToVisio.Utils.AddActions(IEnumerable`1 childActions, Action parent)
   at LinkeD365.FlowToVisio.Utils.AddActions(IEnumerable`1 childActions, Action parent)
   at LinkeD365.FlowToVisio.Utils.AddActions(IEnumerable`1 childActions, Action parent)
   at LinkeD365.FlowToVisio.Utils.AddActions(IEnumerable`1 childActions, Action parent)
   at LinkeD365.FlowToVisio.Utils.AddActions(IEnumerable`1 childActions, Action parent)
   at LinkeD365.FlowToVisio.FlowToVisioControl.GenerateVisio()
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
```

Visio file was created, bu tlocked until I closed the entire XrmToolBox.
File only contained these components, stacked on top of each other (and they are NOT from my flow):

![image](https://user-images.githubusercontent.com/2572253/95987949-6f141580-0e28-11eb-9c18-aeead3527f2e.png)

---
- Deployment: Online
- DB Version: 9.1.0.23470
- Connection Controls Version: 1.2020.5.33
- XrmToolBox Version: 1.2020.10.41
- Tool Version: 1.2020.10.6

**Comment by rappen** [comment]
Retried the procedure from scratch, and the behavior was reproduced.

**Comment by rappen** [comment]
Trying other flows and it works fine.
So something fishy with the first flow I tried...
Can share offline info if requested.

**Comment by LinkeD365** [comment]
please check @rappen

**Comment by LinkeD365** [comment]
Closing as assume it is working now
